# Generated by Django 4.2.1 on 2023-06-25 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatoApp', '0003_materias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materias',
            name='descripcion',
            field=models.TextField(max_length=1000),
        ),
    ]
