# Generated by Django 4.2.1 on 2023-06-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatoApp', '0005_materiasconstrucciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instalaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=180)),
                ('descripcion', models.TextField(max_length=1000)),
            ],
        ),
    ]
