# Generated by Django 4.2.1 on 2023-06-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatoApp', '0008_alter_proyectos_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='instalaciones',
            name='foto1',
            field=models.ImageField(blank=True, null=True, upload_to='instalacionesImages'),
        ),
        migrations.AddField(
            model_name='instalaciones',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='instalacionesImages'),
        ),
        migrations.AddField(
            model_name='instalaciones',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='instalacionesImages'),
        ),
    ]
