# Generated by Django 4.2.1 on 2023-06-25 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tatoApp', '0009_instalaciones_foto1_instalaciones_foto2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='media',
        ),
        migrations.AddField(
            model_name='proyectos',
            name='videoLink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
